vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.lsp"
require "user.none-ls"
require "user.telescope"
require "user.treesitter"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.toggleterm"
require "user.ibl"
require "user.project"
require "user.harpoon"
require "user.dap"
require "user.catpuccin"
